#!/bin/sh 
python evaluate_kernel_features.py kernel_classification_handover_0_4000_all_rnn
python evaluate_kernel_features.py kernel_classification_handover_0_4000_neuhalf_rnn
python evaluate_kernel_features.py kernel_classification_handover_1_4000_all_rnn
python evaluate_kernel_features.py kernel_classification_handover_1_4000_neuhalf_rnn
python evaluate_kernel_features.py kernel_classification_handover_2_4000_all_rnn
python evaluate_kernel_features.py kernel_classification_handover_2_4000_neuhalf_rnn
python evaluate_kernel_features.py kernel_classification_foodPoking_foodPoking_4000_all_rnn
python evaluate_kernel_features.py kernel_classification_foodPoking_foodPoking_4000_neuhalf_rnn
