python evaluate_kernel.py tool20_neutouch_kernel_svmlinear
python evaluate_kernel.py tool20_neutouch_kernel_svmrbf
python evaluate_kernel.py tool20_neutouch_kernel_mlp
python evaluate_kernel.py tool20_neuhalf_kernel_svmlinear
python evaluate_kernel.py tool20_neuhalf_kernel_svmrbf
python evaluate_kernel.py tool20_neuhalf_kernel_mlp
python evaluate_kernel.py tool20_neusingle_kernel_svmlinear
python evaluate_kernel.py tool20_neusingle_kernel_svmrbf

python evaluate_kernel.py tool30_neutouch_kernel_svmlinear
python evaluate_kernel.py tool30_neutouch_kernel_svmrbf
python evaluate_kernel.py tool30_neutouch_kernel_mlp
python evaluate_kernel.py tool30_neuhalf_kernel_svmlinear
python evaluate_kernel.py tool30_neuhalf_kernel_svmrbf
python evaluate_kernel.py tool30_neuhalf_kernel_mlp
python evaluate_kernel.py tool30_neusingle_kernel_svmlinear
python evaluate_kernel.py tool30_neusingle_kernel_svmrbf

python evaluate_kernel.py tool50_neutouch_kernel_svmlinear
python evaluate_kernel.py tool50_neutouch_kernel_svmrbf
python evaluate_kernel.py tool50_neutouch_kernel_mlp
python evaluate_kernel.py tool50_neuhalf_kernel_svmlinear
python evaluate_kernel.py tool50_neuhalf_kernel_svmrbf
python evaluate_kernel.py tool50_neuhalf_kernel_mlp
python evaluate_kernel.py tool50_neusingle_kernel_svmlinear
python evaluate_kernel.py tool50_neusingle_kernel_svmrbf