python evaluate_kernel.py handover_0_kernel_rnn

python evaluate_kernel.py handover_1_kernel_rnn

python evaluate_kernel.py handover_2_kernel_rnn

python evaluate_kernel.py foodPoking_kernel_rnn

python evaluate_kernel.py tool20_neutouch_kernel_rnn
python evaluate_kernel.py tool30_neutouch_kernel_rnn
python evaluate_kernel.py tool50_neutouch_kernel_rnn

