#!/bin/sh 
python evaluate_kernel_features.py kernel_regression_rodTap_20_4000_all_rnn
python evaluate_kernel_features.py kernel_regression_rodTap_20_4000_neuhalf_rnn
python evaluate_kernel_features.py kernel_regression_rodTap_30_4000_all_rnn
python evaluate_kernel_features.py kernel_regression_rodTap_30_4000_neuhalf_rnn
python evaluate_kernel_features.py kernel_regression_rodTap_50_4000_all_rnn
python evaluate_kernel_features.py kernel_regression_rodTap_50_4000_neuhalf_rnn
