python evaluate_kernel.py handover_0_kernel_svmlinear
python evaluate_kernel.py handover_0_kernel_svmrbf
python evaluate_kernel.py handover_0_kernel_mlp
python evaluate_kernel.py handover_0_kernel_rnn

python evaluate_kernel.py handover_1_kernel_svmlinear
python evaluate_kernel.py handover_1_kernel_svmrbf
python evaluate_kernel.py handover_1_kernel_mlp
python evaluate_kernel.py handover_1_kernel_rnn

python evaluate_kernel.py handover_2_kernel_svmlinear
python evaluate_kernel.py handover_2_kernel_svmrbf
python evaluate_kernel.py handover_2_kernel_mlp
python evaluate_kernel.py handover_2_kernel_rnn

python evaluate_kernel.py foodPoking_kernel_svmlinear
python evaluate_kernel.py foodPoking_kernel_svmrbf
python evaluate_kernel.py foodPoking_kernel_mlp
python evaluate_kernel.py foodPoking_kernel_rnn